export const episodeDescriptions = {
  1: "Rick takes Morty on a dangerous mission to collect mega seeds from another dimension.",
  2: "Rick gives Jerry a device to control the dog, but it backfires when the dogs become intelligent.",
  3: "A love potion intended for Jessica mutates the population into monsters.",
  4: "Rick creates a simulation to con alien scammers, but things get out of hand.",
  5: "Rick, Morty, and their teacher travel inside a dying homeless man’s body.",
  6: "The family attends therapy while Rick and Morty fight monsters in a surreal dimension.",
  7: "Morty becomes obsessed with a hive-mind entity while Rick tries to fix his ship.",
  8: "Morty chooses an adventure of his own, which turns out to be extremely violent.",
  9: "Rick installs interdimensional cable, showing alternate reality TV shows.",
  10: "Morty rebels during a rescue mission inside a surreal prison-like dimension.",
  11: "Morty chooses an adventure that leads to a medieval world ruled by numbered castes.",
  12: "The family faces a zombie apocalypse during a summer house party.",
  13: "Rick and Morty are captured and put on trial by the Galactic Federation.",
  14: "Rick messes with time, creating multiple realities that spiral out of control.",
  15: "The family explores Anatomy Park, a theme park inside a human body.",
  16: "Rick turns Jerry into a genius as a favor to Beth, but it doesn’t go as planned.",
  17: "Morty bonds with a sentient crystal that shows his potential deaths.",
  18: "Rick ditches Morty to party on a distant planet with Summer.",
  19: "Rick body-swaps with aliens while Morty struggles to rescue Summer.",
  20: "Rick and Morty escape a maximum-security intergalactic prison.",
  21: "Rick surrenders to the Galactic Federation to protect his family.",
  22: "Rick escapes from prison; the family adjusts to life without him.",
  23: "Parasitic aliens infiltrate the house, implanting fake memories.",
  24: "Rick takes Morty to the Citadel of Ricks, uncovering a dark conspiracy.",
  25: "Beth reconnects with a childhood friend; Rick battles alien invaders.",
  26: "Rick fuses with a cosmic entity, threatening the balance of the universe.",
  27: "Morty gets stuck in a simulation while Rick and Jerry go camping.",
  28: "Summer becomes a giant to confront a group of teenage bullies.",
  29: "Morty becomes obsessed with a death crystal that shows him a perfect future.",
  30: "Rick battles the President over who controls reality.",
  31: "Rick and Morty explore a mysterious space station; Beth and Jerry reconcile.",
  32: "Morty uses emotion-altering beads and destabilizes time.",
  33: "Rick trains a group of Mortys to defeat an artificial intelligence.",
  34: "Rick and Morty ride a story-train that blends narrative and reality.",
  35: "Rick creates decoy families that question their own existence.",
  36: "Morty falls in love with a girl in a post-apocalyptic wasteland.",
  37: "Rick and Beth explore a vault of memories and personal truths.",
  38: "Morty downloads a dangerous dating app made by aliens.",
  39: "Rick turns into a shrimp to avoid galactic enemies.",
  40: "Rick clones Beth, but no one knows which one is the real one.",
  41: "Rick faces his old nemesis Mr. Nimbus; Morty loses control of time.",
  42: "Rick is hunted by evil versions of himself from across the multiverse.",
  43: "Morty bonds with a horse-based society that results in monstrous consequences.",
  44: "Rick gets trapped in a virtual reality game and questions his identity.",
  45: "Rick and Morty jump between dimensions to prevent universal collapse.",
  46: "Rick enters Birdperson’s mind to help him recover from trauma.",
  47: "The family unknowingly lives in a fabricated simulation.",
  48: "Rick and Morty confront clones and imposters of themselves.",
  49: "Rick is betrayed by one of his own AI creations.",
  50: "Morty tries to control fate using a remote, but chaos ensues.",
  51: "Morty faces off against Evil Morty, now president of the Citadel.",
};
